#!/bin/bash

# Add requirements footer to en.md (creates en.published.md) and he.md files

WHATSAPP_LINK="https://whatsapp.com/channel/0029Vb7ZXok5kg7Di82iSt1S"
REPO_BASE="https://github.com/tupe12334/whatsapp-channel/blob/main"

# Process en.md files - create en.published.md instead of mutating
# Prefers en.typos-fixed.md (with typo corrections) over en.md if available
find . -type f -name "en.md" | while read -r file; do
    dir=$(dirname "$file")
    published_file="$dir/en.published.md"
    fixed_file="$dir/en.typos-fixed.md"

    # Prefer en.typos-fixed.md if it exists, otherwise use en.md
    if [ -f "$fixed_file" ]; then
        source_file="$fixed_file"
    else
        source_file="$file"
    fi

    # Check if published file needs to be (re)generated
    should_generate=false
    if [ ! -f "$published_file" ]; then
        should_generate=true
    elif [ "$source_file" -nt "$published_file" ]; then
        should_generate=true
        echo "Source updated: $source_file is newer than $published_file"
    fi

    if [ "$should_generate" = false ]; then
        echo "Skipping: $published_file is up to date"
        continue
    fi

    # Get relative path for repository link (always reference original en.md)
    rel_path="${file#./}"

    echo "Creating: $published_file (from $source_file with footer)"

    # Copy from source and add footer (overwrite, not append)
    cat "$source_file" > "$published_file"
    cat >> "$published_file" << EOF

---

- [ZoomOut WhatsApp Channel]($WHATSAPP_LINK)
- [Source file]($REPO_BASE/$rel_path)
- Translated from English to Hebrew using Claude Code
EOF
done

# Process he.md files - add footer if not already present
# Note: he.md files are regenerated by translate-missing.sh, so we only check for footer existence
find . -type f -name "he.md" | while read -r file; do
    # Skip if file already has the footer (prevents duplicate appends)
    # Use WhatsApp URL for detection - invariant across translations
    if grep -q "$WHATSAPP_LINK" "$file"; then
        echo "Skipping: $file (footer already exists)"
        continue
    fi

    # Get relative path for repository link
    rel_path="${file#./}"

    echo "Adding footer to: $file"

    cat >> "$file" << EOF

---

- [ערוץ ZoomOut WhatsApp]($WHATSAPP_LINK)
- [קובץ המקור]($REPO_BASE/$rel_path)
- תורגם באמצעות Claude Code
EOF
done

echo "Done!"
